services:
  grpc-backend:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    network_mode: "host"

  soap-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - GRPC_HOST=127.0.0.1:50051
    network_mode: "host"
    depends_on:
      - grpc-backend
